package edu.washington.nsre.extraction;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

public class Config {
	public static Properties prop = new Properties();
	public static String configFile = "data/config/nsre.conf";
	public static String dir;
	public static String parallelFile;
	public static String eventsFile;
	public static String keywordsFile;
	public static String candidatesFile;
	public static String tempDirGenerate;
	public static String tempDirHeuristics;
	public static String keywordsAnnotationFile;
	public static String dictionaryFile;
	public static String heuristicNegativeFile;
	public static String heuristicPositiveFile;
	public static String generatedTrainingFile;
	public static String bingWordsDir;
	// public static String keywordHeuristicsFile;
	public static String modelFile;

	public static void parseConfig() throws FileNotFoundException, IOException {
		prop.clear();
		prop.load(new FileReader(Config.configFile));
		dir = Config.prop.getProperty("dir");
		parallelFile = Config.prop.getProperty("parallelFile");
		eventsFile = dir + File.separator + "events";
		bingWordsDir = Config.prop.getProperty("bingWordsDir");
		// users can provide the annotation if they need supervised NewsSpikeRE
		keywordsAnnotationFile = dir + File.separator + Config.prop.getProperty("annotation");

		// files generated by systems
		keywordsFile = dir + File.separator + "keywordsUnlabeled";
		candidatesFile = dir + File.separator + "candidates";
		tempDirGenerate = dir + File.separator + "tempDirGenerate";
		// generated training file
		generatedTrainingFile = dir + File.separator + "generated";
		// learned model
		modelFile = dir + File.separator + "model";
		tempDirHeuristics = dir + File.separator + "tempHeuristics";

		dictionaryFile = dir + File.separator + Config.prop.getProperty("dictionary");
		heuristicNegativeFile = Config.prop.getProperty("heuristicNegative");
		heuristicPositiveFile = Config.prop.getProperty("heuristicPositive");
		// keywordHeuristicsFile = dir + File.separator + "keywordsHeuristics";
	}
}
